[package]
name = "macros"
version = "0.0.0"
edition = "2018"
license = "GPL-2.0-only"

[lib]
path = "lib.rs"
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
